name: "ruby_example"
type: "ruby:2.5"
disk: 1024

hooks:
  build: |
    ruby -v
    which ruby
    bundle -v
    which bundle
    gem install bundler -v '2.0.1'
    which bundle
    bundle -v
    bundle install -V
    rake assets:precompile
  deploy: |
    rails db:migrate

mounts:
  "/log": "shared:files/log"
  "/tmp": "shared:files/tmp"
  "/db": "shared:files/db"

web:
  commands:
    start: 'rails server -p $PORT'
  locations:
    '/':
      root: 'public'
      passthru: true
      allow: true